import { RoomBookingStatus } from '../types';
import { type Room } from '../types/room';

export const mockRooms: Room[] = [
  {
    id: 'P101',
    number: 'P101',
    type: 'Double',
    booking_status: RoomBookingStatus.AVAILABLE,
    status: 1,
    price: 1650000,
    areaId: 0,
    occupants: [
      {
        name: 'John Smith',
        id: 'ID001',
        age: 35,
        gender: 'male',
        isChild: false,
      },
      {
        name: 'Mary Smith',
        id: 'ID002',
        age: 32,
        gender: 'female',
        isChild: false,
      },
      {
        name: 'Tommy Smith',
        id: 'ID003',
        age: 8,
        gender: 'male',
        isChild: true,
      },
    ],
  },
  {
    id: 'P102',
    number: 'P102',
    type: 'Single',
    booking_status: RoomBookingStatus.OCCUPIED,
    status: 1,
    price: 1250000,
    areaId: 0,
    occupants: [
      {
        name: 'John Smith',
        id: 'ID001',
        age: 35,
        gender: 'male',
        isChild: false,
      },
      {
        name: 'Mary Smith',
        id: 'ID002',
        age: 32,
        gender: 'female',
        isChild: false,
      },
      {
        name: 'Tommy Smith',
        id: 'ID003',
        age: 8,
        gender: 'male',
        isChild: true,
      },
    ],
  },
  {
    id: 'P201',
    number: 'P201',
    type: 'Suite',
    booking_status: RoomBookingStatus.RESERVED,
    status: 1,
    price: 2150000,
    areaId: 1,
    occupants: [
      {
        name: 'John Smith',
        id: 'ID001',
        age: 35,
        gender: 'male',
        isChild: false,
      },
      {
        name: 'Mary Smith',
        id: 'ID002',
        age: 32,
        gender: 'female',
        isChild: false,
      },
      {
        name: 'Tommy Smith',
        id: 'ID003',
        age: 8,
        gender: 'male',
        isChild: true,
      },
    ],
  },
  {
    id: 'P202',
    number: 'P202',
    type: 'Double',
    booking_status: RoomBookingStatus.CLEANING,
    status: 1,
    price: 1650000,
    areaId: 1,
    occupants: [
      {
        name: 'John Smith',
        id: 'ID001',
        age: 35,
        gender: 'male',
        isChild: false,
      },
      {
        name: 'Mary Smith',
        id: 'ID002',
        age: 32,
        gender: 'female',
        isChild: false,
      },
      {
        name: 'Tommy Smith',
        id: 'ID003',
        age: 8,
        gender: 'male',
        isChild: true,
      },
    ],
  },
];
